### ISSUE TITLE
Image fails to run when given the full pathname of an image file

### ISSUE THREAD

**Issue by crosswalk-zz** [herval/deepdream-docker#1]
When the deepdream image is run with the full pathname of the input image the below error message is generated

```
libdc1394 error: Failed to initialize libdc1394
Processing file: /home/crosswalk/Pictures/GIMP/dreamtest.jpg
Traceback (most recent call last):
  File "deepdream.py", line 25, in <module>
    img = np.float32(PIL.Image.open('/data/%s' % input_file))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1996, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: '/data//home/crosswalk/Pictures/GIMP/dreamtest.jpg'
```

It looks like a parsing error since there is an extra whack being added before the full pathname for the input image.

**Comment by herval** [comment]
@crosswalk how did you run the docker container? (the full "docker run" command that is)

**Comment by crosswalk-zz** [comment]
```
docker run -i -t -e INPUT=/home/crosswalk/Pictures/GIMP/dreamtest.jpg -v /home/crosswalk/Pictures/GIMP/:/data herval/deepdream
```

Sorry for the delay.

**Comment by herval** [comment]
@crosswalk `INPUT` is just the _name_ of the file. That should work:

```
docker run -i -t -e INPUT=dreamtest.jpg -v /home/crosswalk/Pictures/GIMP/:/data herval/deepdream
```

**Comment by crosswalk-zz** [comment]
Thank you for clarifying. Keep up the good work on this tool. It's great.
