### ISSUE TITLE
Error when running on a 1920x1080px image

### ISSUE THREAD

**Issue by BastianVoigt** [herval/deepdream-docker#11]
E0821 16:05:02.724855     1 upgrade_proto.cpp:618] Attempting to upgrade input file specified using deprecated V1LayerParameter: /caffe/models/bvlc_googlenet/bvlc_googlenet.caffemodel
    I0821 16:05:02.752223     1 upgrade_proto.cpp:626] Successfully upgraded file specified using deprecated V1LayerParameter
    This might take a little while...
    Traceback (most recent call last):
      File "deepdream.py", line 104, in <module>
        step_one = deepdream(net, img)
      File "deepdream.py", line 68, in deepdream
        octaves = [preprocess(net, base_img)]
      File "deepdream.py", line 44, in preprocess
        return np.float32(np.rollaxis(img, 2)[::-1]) - net.transformer.mean['data']
    ValueError: operands could not be broadcast together with shapes (4,1080,1920) (3,1,1)

**Comment by BastianVoigt** [comment]
It also says:

    libdc1394 error: Failed to initialize libdc1394

**Comment by montyanderson** [comment]
I got this error when I gave the parameters incorrectly.

@BastianVoigt Make sure you give the path to the input as relative to the directory.

**Comment by GnarNoire** [comment]
> It also says:
> 
> ```
> libdc1394 error: Failed to initialize libdc1394
> ```

Just I still have yet to get this to work myself thanks for the info! is it working for you now which file line did you have to edit?

Thanks !
