### ISSUE TITLE
error on 240x320 image

### ISSUE THREAD

**Issue by bwanaaa** [herval/deepdream-docker#12]
image is a 200 kb png file in the directory:

`C:/Users/Stefan.DESKTOP-QQLBN9D/Desktop/deepdream-docker-master/pics
`
command issued in powershell:
```
docker run -i -t -e INPUT=Image00001.png -e ITER=20 -e SCALE=0.10 -e MODEL='inception_3b/5x5_reduce' -v C:/Users/Stefan.DESKTOP-QQLBN9D/Desktop/deepdream-docker-master/pics:/data herval/deepdream
```

powershell output:

```
Traceback (most recent call last):
  File "deepdream.py", line 104, in <module>
    step_one = deepdream(net, img)
  File "deepdream.py", line 68, in deepdream
    octaves = [preprocess(net, base_img)]
  File "deepdream.py", line 44, in preprocess
    return np.float32(np.rollaxis(img, 2)[::-1]) - net.transformer.mean['data']
ValueError: operands could not be broadcast together with shapes (4,320,240) (3,1,1)
```

**Comment by GnarNoire** [comment]
I have had issues myself and have not succeded as of yet love to hear of your trouble shooting as we work to fix everything I was running python 3.8 which originally was the issue but still am banging my head against the wall trouble shooting

**Comment by GnarNoire** [comment]
thanks for checking out my page
if you are a nuke person I have working scripts here if interested 
[](https://sebastianbrown.squarespace.com/sebastian-brown-nuke-scripts)

**Comment by GnarNoire** [comment]
https://sebastianbrown.squarespace.com/sebastian-brown-nuke-scripts
