### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by xerc** [herval/deepdream-docker#2]
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
$ boot2docker version
Boot2Docker-cli version: v1.7.1
Git commit: 8fdc6f5
$ vboxmanage --version
5.0.0r101573
```

```
$ ls -al /tmp/carousel-item-*
-rw-r--r--@ 1 xerc  wheel  1857559 26 Jul 15:59 /tmp/carousel-item-1.jpg
-rw-r--r--@ 1 xerc  wheel   657192 26 Jul 15:59 /tmp/carousel-item-3.jpg
-rw-r--r--@ 1 xerc  wheel  2581746 26 Jul 15:59 /tmp/carousel-item-5.jpg
```

```
$ time docker run -i -t -e INPUT=carousel-item-1.jpg -v /tmp:/data herval/deepdream
libdc1394 error: Failed to initialize libdc1394
Processing file: carousel-item-1.jpg
Traceback (most recent call last):
  File "deepdream.py", line 25, in <module>
    img = np.float32(PIL.Image.open('/data/%s' % input_file))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1996, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: '/data/carousel-item-1.jpg'

real    0m1.530s
user    0m0.143s
sys     0m0.008s
```

looks like the image is not transfered to the VM - or did i miss some configuration?

**Comment by xerc** [comment]
=> do not use /tmp

**Comment by herval** [comment]
@xerc from which folder did you run the `docker` command?
It does look like it couldn't mount the /tmp folder...

**Comment by xerc** [comment]
yes - it is posible to mount /tmp - re-checked all the configurations but could not reproduce

**Comment by herval** [comment]
you didn't answer the question - did you run the `docker` command from inside `/tmp`?
also, you said it's possible to mount the folder - how did you verify that?

**Comment by xerc** [comment]
yes : run from /tmp with files in /tmp

**Comment by herval** [comment]
@xerc I could only reproduce that issue when my user is now the owner of the folder - in the `/tmp` case on OSX it's usually `root`'s. Can you try with any folder inside your home (`/Users/<you>/`)?

**Comment by xerc** [comment]
all other combinations - in user-folders - are working for me

Am 07.08.15 um 22:26 schrieb Herval Freire:
