### ISSUE TITLE
dockerfile fails to build

### ISSUE THREAD

**Issue by vogievetsky** [herval/deepdream-docker#6]
fails on: `The command '/bin/sh -c pip install -r python/requirements.txt' returned a non-zero code: 1`

Full failure log:

```
Step 11 : RUN pip install -r python/requirements.txt
 ---> Running in b837abbcfe4d
Downloading/unpacking Cython>=0.19.2 (from -r python/requirements.txt (line 1))
  Running setup.py (path:/tmp/pip_build_root/Cython/setup.py) egg_info for package Cython
    Unable to find pgen, not compiling formal grammar.

    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/lib/python2.7/dist-packages (from -r python/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.13.2 in /usr/lib/python2.7/dist-packages (from -r python/requirements.txt (line 3))
Downloading/unpacking scikit-image>=0.9.3 (from -r python/requirements.txt (line 4))
  Running setup.py (path:/tmp/pip_build_root/scikit-image/setup.py) egg_info for package scikit-image
    Unable to find pgen, not compiling formal grammar.
    No eggs found in /tmp/easy_install-ZwzgcI/Cython-0.24/egg-dist-tmp-wQkzU_ (setup script problem?)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/scikit-image/setup.py", line 146, in <module>
        **extra
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 126, in setup
        dist = setup(**new_attr)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
        Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: cython>=0.21
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.

No eggs found in /tmp/easy_install-ZwzgcI/Cython-0.24/egg-dist-tmp-wQkzU_ (setup script problem?)

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/scikit-image/setup.py", line 146, in <module>

    **extra

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 126, in setup

    dist = setup(**new_attr)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup

    return old_setup(**new_attr)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__

    Distribution.__init__(self, attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: cython>=0.21

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/scikit-image
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install -r python/requirements.txt' returned a non-zero code: 1
```

Any suggestions?

Thank you!

**Comment by herval** [comment]
Hm... Looks like some change in dependencies broke the install process. Should be all good now!
